name: 'Action to execute shell script'
description: 'pull the changes as per the tags'
inputs:
  repo_name:
    required: true
    type: string
  pr_num:
    required: true
    type: number
  changes_to_deploy:
    require: true
    type: string
    
runs:
  using: "composite"
  steps:
  - id: step1
    shell: bash
    name: Releasing the tags 
    run: |
      set -eo pipefail
      org_repo_name=${{ inputs.repo_name }}
      
      org_name=$(echo ${org_repo_name} | cut -d/ -f1) 
      repo_name=$(echo ${org_repo_name} | cut -d/ -f2)
      
      pr_num=${{ inputs.pr_num }}
      
      deploy_changes=${{ inputs.changes_to_deploy }}
      
      echo "repo and org name is $org_repo_name"
      echo "Repo name is $repo_name"  
      echo "PR number is $pr_num"
      echo "Changes to deploy ${deploy_changes}"
      
      for line in ${deploy_changes}
      do
        echo $line
      done
